//
//  StringResources.swift
//  WorkoutApp(pet)
//
//  Created by Danil Pestov on 11.04.2024.
//

import UIKit

struct Const {
    static let signUp = NSLocalizedString("signUp", comment: "")
    static let sighIn = NSLocalizedString("sighIn", comment: "")
    static let mainLabel = NSLocalizedString("signUpTitle", comment: "")
    static let resetPassword = NSLocalizedString("resetPassword", comment: "")
    static let haveAccountText = NSLocalizedString("alreadyHaveAcc", comment: "")
    static let firstName = NSLocalizedString("firstName", comment: "")
    static let lastName = NSLocalizedString("lastName", comment: "")
    static let password = NSLocalizedString("password", comment: "")
    static let confirmPassword = NSLocalizedString("confirmPassword", comment: "")
    static let email = NSLocalizedString("email", comment: "")
    static let resetPasswordInfo = NSLocalizedString("resetPasswordInfo", comment: "")
    static let stats = NSLocalizedString("handbook", comment: "")
    static let notes = NSLocalizedString("notes", comment: "")
    static let tracking = NSLocalizedString("trackingTitle", comment: "")
    static let profile = NSLocalizedString("profile", comment: "")
    static let age = NSLocalizedString("age", comment: "")
    static let gender = NSLocalizedString("gender", comment: "")
    static let weight = NSLocalizedString("weight", comment: "")
    static let height = NSLocalizedString("height", comment: "")
    static let noName = NSLocalizedString("noName", comment: "")
    static let noAge = NSLocalizedString("NoAge", comment: "")
    static let noWeight = NSLocalizedString("noWeight", comment: "")
    static let noHeight = NSLocalizedString("noHeight", comment: "")
    static let noGender = NSLocalizedString("noGender", comment: "")
    static let BMI = NSLocalizedString("BMI", comment: "")
    static let nonHeightAndWeight = NSLocalizedString("nonHeightAndWeight", comment: "")
    static let BMILowIntex = NSLocalizedString("BMIDescriptionLow", comment: "")
    static let BMINormalIndex = NSLocalizedString("BMIDescriptionNormal", comment: "")
    static let BMIOverweightIndex = NSLocalizedString("BMIDescriptionHight", comment: "")
    static let BMIVeryOverweightIndex = NSLocalizedString("BMIDescriptionOverHight", comment: "")
    
    static let years = NSLocalizedString("years", comment: "")
    static let kg = NSLocalizedString("kg", comment: "")
    static let cm = NSLocalizedString("cm", comment: "")
    static let logOut = NSLocalizedString("logOut", comment: "")
    static let myProfile = NSLocalizedString("myProfile", comment: "")
    static let edit = NSLocalizedString("edit", comment: "")
    static let editProfile = NSLocalizedString("editProfile", comment: "")
    static let save = NSLocalizedString("save", comment: "")
    static let selectPhoto = NSLocalizedString("selectPhoto", comment: "")
    static let male = NSLocalizedString("male", comment: "")
    static let female = NSLocalizedString("female", comment: "")
    static let sets = NSLocalizedString("sets", comment: "")
    static let reps = NSLocalizedString("reps", comment: "")
    static let min = NSLocalizedString("min", comment: "")
    static let cancel = NSLocalizedString("cancel", comment: "")
    static let yourPhoto = NSLocalizedString("yourPhoto", comment: "")
    static let muscle = NSLocalizedString("muscle", comment: "")
    static let exerciseName = NSLocalizedString("exerciseName", comment: "")
    static let numberOfSets = NSLocalizedString("sets", comment: "")
    static let numberOfReps = NSLocalizedString("reps", comment: "")
    static let restTime = NSLocalizedString("restTime", comment: "")
    static let trainingName = NSLocalizedString("trainingName", comment: "")
    static let loading = NSLocalizedString("loading", comment: "")
    static let addNewExercise = NSLocalizedString("addNewExercise", comment: "")
    static let addNote = NSLocalizedString("addNote", comment: "")
    static let back = NSLocalizedString("back", comment: "")
    static let delete = NSLocalizedString("delete", comment: "")
    static let newNote = NSLocalizedString("newNote", comment: "")
    static let title = NSLocalizedString("title", comment: "")
    static let sport = NSLocalizedString("sport", comment: "")
    static let nutrition = NSLocalizedString("nutrition", comment: "")
    static let others = NSLocalizedString("others", comment: "")
    static let dailyGoalButtonTitle = NSLocalizedString("dailyGoalButtonTitle", comment: "")
    static let goalTitle = NSLocalizedString("goalTitle", comment: "")
    static let noChartDataTitle = NSLocalizedString("noChartDataTitle", comment: "")
    static let stepCounterMainTitle = NSLocalizedString("stepCounterMainTitle", comment: "")
    static let setDailyGoalTitle = NSLocalizedString("setDailyGoalTitle", comment: "")
    static let numberOfStepsTitle = NSLocalizedString("numberOfStepsTitle", comment: "")

    //Alert resources
    static let fillAllFields = NSLocalizedString("fillAllFields", comment: "")
    static let emptyFields = NSLocalizedString("emptyFields", comment: "")
    static let incorrectFilling = NSLocalizedString("incorrectFilling", comment: "")
    static let alertTitle = NSLocalizedString("alertTitle", comment: "")
    static let okAction = NSLocalizedString("okAction", comment: "")
    static let cancelAction = NSLocalizedString("cancelAction", comment: "")
    static let enterEmail = NSLocalizedString("enterEmail", comment: "")
    static let resetPassInfo = NSLocalizedString("resetPassInfo", comment: "")
    static let needLogIn = NSLocalizedString("needLogIn", comment: "")



}
